parameters:
  environment: ''

stages:
  - stage: Clean
    displayName: Cleaning
    dependsOn: [Deploy]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DestroyResources
        displayName: Cleanup Resources
        steps:
          - task: AzureCLI@2
            displayName: Destroy $(basename)
            inputs:
              azureSubscription: dev
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group delete -n $(basename)
