parameters:
  environment: 'ci'

stages:
  - stage: Clean
    displayName: Cleaning
    dependsOn: [Deploy]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DestroyResources
        displayName: Cleanup Resources
        steps:
          - bash: az group delete -n $(basename)-$(Build.BuildId)
            displayName: Destroy $(basename)-$(Build.BuildId)
