parameters:
  environment: ""

stages:
  - stage: Deploy
    displayName: Deploying
    dependsOn: [Build]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DeployResources
        displayName: Deploy Resources
        steps:
          - bash: az group create --location $(rgLocation) --name $(basename)
            displayName: Deploy $(basename)
