parameters:
  environment: ''

stages:
  - stage: Deploy
    displayName: Deploying
    dependsOn: [Build]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DeployResourceGroup
        displayName: Deploy Resource Group
        steps:
          - bash: az group create --location $(location) --name $(basename)
            displayName: Deploy $(basename)

      - job: DeployResources
        displayName: Deploy Resources
        steps:
          - template: ../steps/deploy-parse-arm.yml
            parameters:
              displayName: Deploy resources for $(basename)
              azureSubscription: $(azure_service_connection_name)
              resourceGroupName: $(basename)
              location: $(location)
              overrideParameters: >
                -basename "$(basename)"
              armFile: ./deploy/azuredeploy.json
