parameters:
  environment: 'ci'

stages:
  - stage: Deploy
    displayName: Deploying
    dependsOn: [Build]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DeployResourceGroup
        displayName: Deploy Resource Group
        steps:
          - bash: az group create --location $(rgLocation) --name $(basename)-$(Build.BuildId)
            displayName: Deploy $(basename)-$(Build.BuildId)
      - job: DeployResources
        displayName: Deploy Resources
        steps:
          - bash: az deployment group create --resource-group $(basename)-$(Build.BuildId) --template-file ./build.yml
            displayName: Deploy resources for $(basename)-$(Build.BuildId)
